const variations = {
  Bush: {
    Bush: {
      sides: 17,
      bases: 39,
      spread: 2,
      growth: 1.5,
      thickness: -1,
      cameraY: 10,
      cameraX: 30,
      chart: '7,6,7,4,6',
      impacts: 'sides',
      colorFrom: '#554400',
      colorTo: '#336600',
      bgColor: '#4499ee',
      gapAxis: 'x',
      duration: 5,
    },
    Cake: {
      sides: 17,
      bases: 39,
      spread: 14.3,
      growth: 1.4,
      thickness: 1,
      itemModifier: 1,
      impacts: 'spread',
      itemOperation: '/',
      chart: '7,6,7,4',
      colorFrom: '#ee5588',
      colorTo: '#eebb55',
      bgColor: '#24a6a8',
      duration: 3,
    },
    Muffin: {
      sides: 20,
      bases: 74,
      spread: 3.5,
      growth: -0.5,
      thickness: 1.7,
      itemModifier: 0.4,
      cameraY: 22,
      chart: '4',
      impacts: 'spread',
      colorFrom: '#664400',
      colorTo: '#886622',
      bgColor: '#eecc00',
    },
    IceCream: {
      sides: 8,
      bases: 92,
      spread: -0.1,
      growth: 1.9,
      thickness: 1.5,
      itemModifier: 1,
      impacts: 'spread',
      itemOperation: '*',
      chart: '7,6,4,2,1,3,2,7,6,1,9,7,4',
      colorFrom: '#eecc00',
      colorTo: '#884400',
      bgColor: '#99aa44',
      gapAxis: 'z',
    },
  },
  Umbrella: {
    Umbrella: {
      sides: 10,
      bases: 10,
      fold: 0.1,
      thickness: 0.5,
      height: 20,
      growth: 0.9,
      xScale: 10,
      yScale: 5,
      itemModifier: 1,
      impacts: 'fold',
      itemOperation: '*',
      chart: '7',
      colorFrom: '#ffcc00',
      colorTo: '#3355dd',
      bgColor: '#118833',
    },
    Spear: {
      sides: 10,
      bases: 16,
      fold: 1.22,
      thickness: 0.3,
      height: 20,
      growth: 0.5,
      xScale: 0.9,
      yScale: 5,
      itemModifier: 0.4,
      gapModifier: 2.5,
      impacts: 'growth',
      chart: '7,6,4,7,6,7,4',
      colorFrom: '#8888aa',
      colorTo: '#666688',
      bgColor: '#331122',
      gapAxis: 'z',
    },
    Pencil: {
      sides: 8,
      bases: 3,
      fold: 0.74,
      thickness: 1.2,
      height: 8.9,
      growth: -0.1,
      xScale: 1.1,
      yScale: 5,
      itemModifier: 1,
      impacts: 'yScale',
      itemOperation: '*',
      gapModifier: 0.5,
      chart: '1,1,1,1,1',
      bgColor: '#335511',
    },
    Plunger: {
      sides: 10,
      bases: 16,
      fold: 1.52,
      thickness: 0.4,
      height: -8.6,
      growth: 1,
      xScale: 4.9,
      yScale: 5,
      chart: '1',
      colorFrom: '#121212',
      colorTo: '#525262',
      bgColor: '#8899aa',
    },
    Rocket: {
      sides: 16,
      bases: 4,
      fold: 1.35,
      thickness: 0.8,
      height: 2.6,
      growth: -0.2,
      gapModifier: 0.3,
      xScale: 1,
      yScale: 9.8,
      chart: '2,4',
      colorFrom: '#821212',
      colorTo: '#a25262',
      bgColor: '#222222',
    },
  },
  PeeCurl: {
    PeeCurl: {
      sides: 10,
      bases: 50,
      spread: 7,
      curvature: 1,
      thickness: 1,
      height: 20,
      growth: 1,
      chart: '1',
      colorFrom: '#888899',
      colorTo: '#9999aa',
    },
    Staircase: {
      sides: 4,
      bases: 32,
      spread: 6,
      curvature: 0,
      thickness: 1.3,
      height: 0.05,
      growth: 0.4,
      itemModifier: 1,
      impacts: 'bases',
      itemOperation: '*',
      chart: '3',
      colorFrom: '#925262',
      colorTo: '#a25262',
    },
    Amphitheater: {
      sides: 9,
      bases: 62,
      spread: 8,
      curvature: 3.5,
      thickness: 0.7,
      height: 5.8,
      growth: 0.1,
      cameraY: 17,
      chart: '1',
      colorFrom: '#888877',
      colorTo: '#777766',
    },
  },
}

export default variations
