const variations = {
  Bush: {
    Bush: {
      sides: 17,
      bases: 39,
      spread: 2,
      growth: 1.5,
      thickness: -1,
      cameraY: 20,
    },
    Cake: {
      sides: 17,
      bases: 39,
      spread: 4.3,
      growth: 1.4,
      thickness: 1,
    },
    Muffin: {
      sides: 20,
      bases: 74,
      spread: 3.5,
      growth: -0.5,
      thickness: 1.7,
    },
    IceCream: {
      sides: 8,
      bases: 92,
      spread: -0.1,
      growth: 1.9,
      thickness: 1.5,
      modifier: 1,
      impacts: 'spread',
      operation: '*',
      chart: '7, 6, 4, 2, 1, 3, 2, 7, 6, 1, 9, 7, 4',
    },
  },
  Umbrella: {
    Umbrella: {
      sides: 10,
      bases: 10,
      fold: 1,
      thickness: 0.5,
      height: 20,
      growth: 0.9,
      xScale: 10,
      yScale: 5,
      modifier: 1,
      impacts: 'fold',
      operation: '*',
      chart: '7, 6, 4, 2, 1, 3, 2, 7, 6, 1, 9, 7, 4',
    },
    Spear: {
      sides: 10,
      bases: 16,
      fold: 1.52,
      thickness: 0.3,
      height: 20,
      growth: 0.5,
      xScale: 0.9,
      yScale: 5,
    },
    Pencil: {
      sides: 8,
      bases: 3,
      fold: 0.74,
      thickness: 1.2,
      height: 8.9,
      growth: -0.1,
      xScale: 1.1,
      yScale: 3,
      modifier: 1,
      impacts: 'height',
      operation: '*',
      chart: '7, 6, 4, 2, 1, 3, 2, 7, 6, 1, 9, 7, 4',
    },
    Plunger: {
      sides: 10,
      bases: 16,
      fold: 1.52,
      thickness: 0.4,
      height: -8.6,
      growth: 1,
      xScale: 4.9,
      yScale: 5,
    },
    Rocket: {
      sides: 16,
      bases: 4,
      fold: 1.35,
      thickness: 0.8,
      height: 12.6,
      growth: -0.2,
      xScale: 1,
      yScale: 9.8,
    },
  },
  PeeCurl: {
    PeeCurl: {
      sides: 10,
      bases: 50,
      spread: 7,
      curvature: 1,
      thickness: 1,
      height: 20,
      growth: 1,
    },
    Staircase: {
      sides: 4,
      bases: 32,
      spread: 6,
      curvature: '0.0',
      thickness: 1.3,
      height: 0.1,
      growth: 0.4,
      cameraZ: 0.7,
      modifier: 1,
      impacts: 'bases',
      operation: '*',
      chart: '7, 6, 4, 2, 1, 3, 2, 7, 6, 1, 9, 7, 4',
    },
    Amphitheater: {
      sides: 9,
      bases: 62,
      spread: 8,
      curvature: 3.5,
      thickness: 0.7,
      height: 5.8,
      growth: 0.1,
      cameraY: 17,
    },
  },
}

export default variations
